global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - docker.for.mac.host.internal:8080
#      - localhost:8080

#  - job_name: 'harbor'
#    scrape_interval: 10s
#    metrics_path: /probe
#    static_configs:
#    - targets: ['docker.for.mac.host.internal:9100']
#      labels:
#          group: 'harbor'
