version: '3.5'
services:
    prom:
        image: prom/prometheus
        container_name: prom
        volumes:
            - ./config.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
