version: '3.5'
services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        volumes:
            - ./data:/var/lib/grafana
            - ./dashboards:/var/lib/grafana/dashboards
            - ./provisioning/datasources/prom.yaml:/etc/grafana/provisioning/datasources/prom.yaml
            - ./provisioning/dashboards/providers.yaml:/etc/grafana/provisioning/dashboards/providers.yaml
        ports:
            - 3000:3000
