version: '3.5'
services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        volumes:
            - ./data:/var/lib/grafana
            - ./provisioning/datasources/prom.yaml:/etc/grafana/provisioning/datasources/prom.yaml
        ports:
            - 3000:3000
